[project]
name = "myagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.12.10",
    "mypy>=1.15.0",
    "nest-asyncio>=1.6.0",
    "pydantic>=2.10.6",
    "pydantic-ai>=0.0.24",
]
